version: "2.2"

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    volumes: 
      - certs:/usr/share/logstash/certs
      - ./configs/logstash-configs/:/usr/share/logstash/config/
      - ./configs/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/:/home/logstash/
      