version: "2.2"

services:
  enterprisesearch:
    image: docker.elastic.co/enterprise-search/enterprise-search:${STACK_VERSION}
    volumes:
      - certs:/usr/share/enterprise-search/config/certs
      - enterprisesearchdata:/usr/share/enterprise-search/config
      - ./configs/enterprise-search.yml:/usr/share/enterprise-search/config/enterprise-search.yml
    ports:
      - ${ENTERPRISE_SEARCH_PORT}:3002
    environment:
      - SERVERNAME=enterprisesearch
      - ENCRYPTION_KEYS=${ENCRYPTION_KEYS}
      - ES_HOST=https://es01:9200
      - ES_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_HOST=http://kibana:5601
    mem_limit: ${MEM_LIMIT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl -s -I http://localhost:3002 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

volumes:
  certs:
    external: true
    name: es_certs
  enterprisesearchdata:
    driver: local